Algoritmo "MeuNome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/01/2025
Var
// Seção de Declarações das variáveis 
   Nome: Caractere

Inicio
   Escreva ("Digite seu nome: ")
   Leia (Nome)
   Escreva ("Muito Prazer ", Nome)
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo