Algoritmo "primeiro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/01/2025
Var
// Seção de Declarações das variáveis 
   msg: Caractere

Inicio
   msg <- "Olá, Mundo!"
   Escreval ("Mensagem ", msg)
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo